import os
import geopandas as gpd
import pandas as pd
from sklearn.metrics import precision_score, recall_score, accuracy_score
import numpy as np

import rasterio
from rasterio.windows import Window
from rasterio.mask import mask
from shapely.geometry import box
import matplotlib.pyplot as plt

import math

def sample_vectors_to_points(
        points_path,
        canopy_vector_dir,
        green_vector_dir,
        samples_column='model_prediction',
        output_path=None
):
    """
    Spatially joins ground truth points with predicted vector polygons.

    Hierarchy Logic:
    - Default: Class 3 (Neither)
    - Intersects Green Vector: Class 2
    - Intersects Canopy Vector: Class 1 (Overwrites Green)
    """
    # 1. Ingest Ground Truth Points
    points = gpd.read_file(points_path)

    # Identify the .shp files in the provided directories
    # Assumes the standard names generated by postprocessing.py
    canopy_shp = os.path.join(canopy_vector_dir, "canopy.shp")
    green_shp = os.path.join(green_vector_dir, "green_cover.shp")

    # Initialize the prediction column with the 'Neither' baseline
    points[samples_column] = 3

    # Store original index to ensure we map joined data back correctly
    points['orig_id'] = points.index

    # 2. Process Green Cover (Class 2)
    if os.path.exists(green_shp):
        green_gdf = gpd.read_file(green_shp)

        # Automatic CRS Alignment
        if points.crs != green_gdf.crs:
            points = points.to_crs(green_gdf.crs)

        # Spatial Join: Points intersecting Green polygons
        joined_green = gpd.sjoin(points, green_gdf, how='inner', predicate='intersects')

        # Update points that were found inside green polygons
        points.loc[joined_green['orig_id'], samples_column] = 2
    else:
        print(f"Warning: Green vector not found at {green_shp}")

    # 3. Process Canopy Cover (Class 1) - THE OVERWRITE STEP
    if os.path.exists(canopy_shp):
        canopy_gdf = gpd.read_file(canopy_shp)

        if points.crs != canopy_gdf.crs:
            points = points.to_crs(canopy_gdf.crs)

        # Spatial Join: Points intersecting Canopy polygons
        joined_canopy = gpd.sjoin(points, canopy_gdf, how='inner', predicate='intersects')

        # Update points. This naturally overrides 2 (Green) with 1 (Canopy)
        points.loc[joined_canopy['orig_id'], samples_column] = 1
    else:
        print(f"Warning: Canopy vector not found at {canopy_shp}")

    if output_path:
        # Ensure the directory exists
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        # Save as GeoPackage
        points.to_file(output_path, driver='GPKG')
        print(f"Sampled points successfully saved to: {output_path}")

    # Drop the temporary ID and return
    return points.drop(columns=['orig_id'])


# =====================================================================
# 1. DATA GENERATION (Saveable to CSV)
# =====================================================================

def get_confusion_matrix_csv(points_df, label_column, pred_column, manual_names, model_names, unsure_labels):
    """
    Processes spatial join results into a raw summary table.
    Returns a standard Pandas DataFrame (perfect for .to_csv()).
    """
    df = points_df.copy()

    # Map IDs to Names
    df['Manual Classification'] = df[label_column].map(manual_names)
    df['Modelled Classification'] = df[pred_column].map(model_names)

    # Determine Status (Match, Unsure, or Error)
    def determine_status(row):
        m_id = row[label_column]
        p_id = row[pred_column]

        if m_id in unsure_labels:
            return 'Unsure'

        # Match logic based on Westminster rules
        if p_id == 3 and m_id in [4, 6]: return 'Match'  # Non-green vs Manmade/Water
        if p_id == 2 and m_id in [1, 2]: return 'Match'  # Green cover vs Veg/Bare Ground
        if p_id == 1 and m_id == 0:      return 'Match'  # Tree canopy vs Tree

        return 'Error'

    df['Status'] = df.apply(determine_status, axis=1)

    # Grouping and Calculations
    table = df.groupby(['Manual Classification', 'Modelled Classification', 'Status']).size().reset_index(
        name='Number of Points')

    # Calculate Percentage (Raw float for now, formatting happens in Styler)
    table['Percentage'] = (table['Number of Points'] / len(df) * 100)

    # SORTING: Order based on highest frequency (Number of Points) descending
    table = table.sort_values(by='Number of Points', ascending=False).reset_index(drop=True)

    return table


# =====================================================================
# 2. VISUAL STYLING (For Notebook Display)
# =====================================================================

def style_confusion_matrix(df):
    """
    Applies GLA-style formatting and colors to the accuracy summary table.
    Expects a DataFrame generated by get_confusion_matrix_csv.
    """

    def gla_styling(row):
        colors = {
            'Match': 'background-color: #c6efce',  # Green
            'Unsure': 'background-color: #ffeb9c',  # Yellow
            'Error': 'background-color: #ffc7ce'  # Red
        }
        return [colors.get(row['Status'], '')] * len(row)

    styler = (
        df.style
            .apply(gla_styling, axis=1)
            .format({'Percentage': '{:.1f}'})  # FIX: 1 decimal place
            .set_properties(**{
            'border': '1px solid black',  # FIX: Adds grid lines
            'text-align': 'center'
        })
            .set_table_styles([
            # Ensures headers have black borders to match the GLA report style
            {'selector': 'th', 'props': [('border', '1px solid black'), ('background-color', '#f2f2f2')]}
        ])
            .hide(axis='index')
            .set_table_attributes('style="margin-left: auto; margin-right: auto;"')
    )

    return styler


# =====================================================================
# 3. TABLE 2 DATA GENERATION (Generalizable & Multi-Class)
# =====================================================================


def get_accuracy_metrics_csv(points_df, label_column, pred_column, config):
    """
    Calculates metrics for Table 2, ensuring GLA's strict 'Worst Case' forced errors.
    """
    df = points_df.copy()
    total_points = len(df)
    data = []

    for map_name, rules in config.items():
        # 1. Base Binary Masks
        y_true = df[label_column].isin(rules['Manual Positives']).astype(int)
        y_pred = df[pred_column].isin(rules['Model Positives']).astype(int)

        # 2. THE FIX: Force Errors for Worst Case Scenario
        # This mirrors your unrefined notebook: true = 1 - pred
        error_mask = df[label_column].isin(rules['Forced Error Labels'])
        y_true.loc[error_mask] = 1 - y_pred.loc[error_mask]

        # 3. Calculate Class Metrics (Precision/Recall)
        pos_cons = precision_score(y_true, y_pred, pos_label=1, zero_division=0)
        pos_prod = recall_score(y_true, y_pred, pos_label=1, zero_division=0)
        neg_cons = precision_score(y_true, y_pred, pos_label=0, zero_division=0)
        neg_prod = recall_score(y_true, y_pred, pos_label=0, zero_division=0)

        # 4. Overall Worst Case Accuracy
        overall_worst = accuracy_score(y_true, y_pred)

        # 5. Overall Realistic Adjustment
        # Calculate how many points were strictly correct without the forced errors
        base_correct_mask = ~error_mask & (y_true == y_pred)
        base_correct_count = base_correct_mask.sum()

        adj_points = len(df[df[label_column] == rules['Adjustment Label']])
        overall_real = (base_correct_count + (0.5 * adj_points)) / total_points

        # 6. Build the rows
        data.append({
            'Map': map_name, 'Option': rules['Positive Option'],
            'Consumer accuracy': pos_cons, 'Producer accuracy': pos_prod,
            'Overall (Worst case)': overall_worst, 'Overall (Realistic scenario)': overall_real
        })
        data.append({
            'Map': map_name, 'Option': rules['Negative Option'],
            'Consumer accuracy': neg_cons, 'Producer accuracy': neg_prod,
            'Overall (Worst case)': None, 'Overall (Realistic scenario)': None
        })

    return pd.DataFrame(data)


# =====================================================================
# 4. TABLE 2 STYLING (Hierarchical Indexing)
# =====================================================================

def style_accuracy_metrics(df):
    """
    Applies GLA-style formatting to Table 2 using MultiIndex.
    Fixed: Aligns all headers on a single row while maintaining merged cells.
    """
    # 1. Formatting dictionary
    format_dict = {
        'Consumer accuracy': '{:.0%}',
        'Producer accuracy': '{:.0%}',
        'Overall (Worst case)': '{:.0%}',
        'Overall (Realistic scenario)': '{:.0%}'
    }

    # 2. Set the MultiIndex for the 'spanning' effect
    # We strip the names temporarily to fix the header alignment issue
    display_df = df.set_index(['Map', 'Option'])
    display_df.index.names = [None, None]

    styler = (
        display_df.style
        .format(format_dict, na_rep='')
        .set_properties(**{
            'border': '1px solid black',
            'text-align': 'center'
        })
        # Bold the realistic scenario column
        .set_properties(subset=['Overall (Realistic scenario)'], **{'font-weight': 'bold'})
        .set_table_styles([
            # THE FIX: This targets the empty top-left corners and headers
            {'selector': 'th', 'props': [
                ('border', '1px solid black'),
                ('background-color', '#f2f2f2'),
                ('vertical-align', 'middle'),
                ('text-align', 'center')
            ]},
            # Add the labels back into the 'index' headers manually via CSS content if needed,
            # or just rely on the clean alignment.
            {'selector': 'th.row_heading', 'props': [('text-align', 'left'), ('font-weight', 'bold')]}
        ])
        .set_table_attributes('style="margin-left: auto; margin-right: auto;"')
    )

    return styler



# =====================================================================
# DYNAMIC WINDOW CALCULATOR
# =====================================================================

def get_spatial_test_window(tile_height, tile_width, train_ratio=0.7, test_gap_px=5):
    """
    Calculates the exact rasterio Window for the testing set, mirroring the
    mathematical logic of the spatial split used during model training.
    """
    train_end_row = int(tile_height * train_ratio)
    test_start_row = train_end_row + test_gap_px
    test_height = tile_height - test_start_row

    print(f"Returned Rasterio object: Window({0}, {test_start_row}, {tile_width}, {test_height}) ")

    return Window(col_off=0, row_off=test_start_row, width=tile_width, height=test_height)


# =====================================================================
# FINAL COVER & ERROR ANALYSIS (Vector Based)
# =====================================================================

def _compute_vector_cover_percentage(vector_gdf, boundary_gdf):
    """Internally calculates the base % cover of a vector within a geographic boundary."""
    vector_gdf = vector_gdf.to_crs(boundary_gdf.crs)
    clipped_vector = gpd.clip(vector_gdf, boundary_gdf)

    total_feature_area = clipped_vector.geometry.area.sum()
    total_boundary_area = boundary_gdf.geometry.area.sum()

    return (total_feature_area / total_boundary_area) * 100


def _get_vector_vs_raster_errors(vector_gdf, labelled_tiles, target_raster_vals, testing_window=None):
    """
    Internally calculates bias errors and patch areas dynamically.
    If testing_window is provided, only that specific pixel strip is evaluated.
    """
    errors = []
    patch_areas_ha = []

    for tile_path in labelled_tiles:
        with rasterio.open(tile_path) as src:
            # 1. Read ground truth and define patch bounds
            if testing_window:
                l_data = src.read(1, window=testing_window)
                patch_geom = box(*src.window_bounds(testing_window))
            else:
                l_data = src.read(1)
                patch_geom = box(*src.bounds)

            # 2. Area in Hectares
            patch_area = patch_geom.area / 10000.0
            patch_areas_ha.append(patch_area)

            # 3. Ground Truth %
            true_pct = np.isin(l_data, target_raster_vals).mean() * 100

            # 4. Model % (Intersect Vector with the Patch Bounding Box)
            patch_gdf = gpd.GeoDataFrame({'geometry': [patch_geom]}, crs=src.crs)
            vector_gdf = vector_gdf.to_crs(src.crs)
            clipped_features = gpd.clip(vector_gdf, patch_gdf)

            model_pct = (clipped_features.geometry.area.sum() / patch_geom.area) * 100

            # 5. Error
            errors.append(model_pct - true_pct)

    return np.array(errors), np.array(patch_areas_ha)


def evaluate_final_cover_and_errors(canopy_vector_path, green_vector_path, boundary_vector_path,
                                    labelled_tiles, plot_output_path, testing_window=None):
    """
    Master function: Computes final cover %, extracts errors, calculates SE, and plots convergence.
    """
    # 1. Load Data
    canopy_gdf = gpd.read_file(canopy_vector_path)
    green_gdf = gpd.read_file(green_vector_path)
    boundary_gdf = gpd.read_file(boundary_vector_path)

    # 2. Compute Base Cover Percentages
    c_base_cover = _compute_vector_cover_percentage(canopy_gdf, boundary_gdf)
    g_base_cover = _compute_vector_cover_percentage(green_gdf, boundary_gdf)

    # 3. Calculate Errors
    c_errs, c_areas = _get_vector_vs_raster_errors(canopy_gdf, labelled_tiles, [1], testing_window)
    g_errs, g_areas = _get_vector_vs_raster_errors(green_gdf, labelled_tiles, [1, 2], testing_window)

    # 4. Convergence Statistics
    def get_stats(errors):
        means = [np.mean(errors[:i]) for i in range(1, len(errors) + 1)]
        stds = [np.std(errors[:i]) for i in range(1, len(errors) + 1)]
        rms = [np.sqrt(np.mean(errors[:i] ** 2)) for i in range(1, len(errors) + 1)]
        return means, stds, rms

    c_means, c_stds, c_rms = get_stats(c_errs)
    g_means, g_stds, g_rms = get_stats(g_errs)

    # 5. Calculate Standard Error (SE)
    total_area_ha = boundary_gdf.geometry.area.sum() / 10000.0
    avg_patch_ha = np.mean(c_areas)
    n_patches = total_area_ha / avg_patch_ha

    se_canopy = abs(c_means[-1]) + (c_stds[-1] / np.sqrt(n_patches))
    se_green = abs(g_means[-1]) + (g_stds[-1] / np.sqrt(n_patches))

    # 6. Plotting
    os.makedirs(os.path.dirname(plot_output_path), exist_ok=True)
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True)
    cumulative_ha = np.cumsum(c_areas)

    ax1.errorbar(cumulative_ha, c_means, yerr=c_stds, fmt='-ob', capsize=5, label='Canopy Mean Error')
    ax1.errorbar(cumulative_ha, g_means, yerr=g_stds, fmt='-og', capsize=5, label='Green Cover Mean Error')
    ax1.set_ylabel("Absolute Error (%)")
    ax1.set_title("Error Convergence")
    ax1.legend()
    ax1.grid(alpha=0.3)

    ax2.plot(cumulative_ha, c_rms, '--*b', label='Canopy RMS Error')
    ax2.plot(cumulative_ha, g_rms, '--*g', label='Green Cover RMS Error')
    ax2.set_ylabel("RMS Error (%)")
    ax2.set_xlabel("Cumulative Testing Area (Hectares)")
    ax2.legend()
    ax2.grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig(plot_output_path, dpi=300, bbox_inches='tight')
    plt.show()

    return {
        'Canopy Cover': c_base_cover, 'Canopy SE': se_canopy,
        'Green Cover': g_base_cover, 'Green SE': se_green,
        'Total Area (Ha)': total_area_ha
    }


# =====================================================================
# 6. iTREE STATISTICAL COVER ESTIMATION
# =====================================================================

def calculate_itree_cover(points_df, label_col, manual_names, verbose=True):
    """
    Calculates statistical Canopy and Green Cover based on the iTree
    proportion-assignment methodology.

    Args:
        points_df: GeoDataFrame or DataFrame containing the point labels.
        label_col: The string name of the column containing numeric labels.
        manual_names: Dictionary mapping numeric codes to their string names.
        verbose: Boolean to print the step-by-step mathematical breakdown.

    Returns:
        Dictionary containing the final estimated cover percentages.
    """
    # 1. Map the numeric labels to their readable strings immediately
    mapped_series = points_df[label_col].map(manual_names)
    raw_counts = mapped_series.value_counts(normalize=True) * 100

    if verbose:
        table_df = pd.DataFrame({'Raw Percentage (%)': raw_counts}).round(2)
        table_df.index.name = None  # FIX: Removes the misaligned 'landuse_label' index name

        print("--- RAW LABEL PERCENTAGES ---")
        print(table_df)
        print("\n" + "=" * 40 + "\n")

    # 2. Extract specific percentages dynamically using the human-readable strings
    pct_tree = raw_counts.get('Tree', 0.0)
    pct_veg_not_tree = raw_counts.get('Vegetation (not Tree)', 0.0)
    pct_bare = raw_counts.get('Bare Ground', 0.0)
    pct_veg_unsure = raw_counts.get('Vegetation (unsure if Tree)', 0.0)
    pct_unsure_total = raw_counts.get('Unsure', 0.0)

    # --- 3. CANOPY COVER CALCULATION ---
    if verbose: print("--- CANOPY COVER ESTIMATE ---")

    # Step A: Proportion of trees within known vegetation
    known_veg = pct_tree + pct_veg_not_tree
    tree_ratio = pct_tree / known_veg if known_veg > 0 else 0

    if verbose:
        print(f"Step A: Find tree proportion in known vegetation")
        print(
            f"Total known vegetation = {pct_tree:.2f}% (Tree) + {pct_veg_not_tree:.2f}% (Veg not Tree) = {known_veg:.2f}%")
        print(f"Proportion = {pct_tree:.2f} / {known_veg:.2f} = {tree_ratio:.4f}")

    # Step B: Apply proportion to unsure vegetation
    est_hidden_trees = pct_veg_unsure * tree_ratio

    if verbose:
        print(f"\nStep B: Estimate hidden trees")
        print(
            f"Estimated hidden trees = {pct_veg_unsure:.2f}% (Veg unsure if Tree) * {tree_ratio:.4f} = {est_hidden_trees:.2f}%")

    # Step C: Final Canopy Cover
    final_canopy = pct_tree + est_hidden_trees

    if verbose:
        print(f"\nStep C: Final Canopy Cover")
        print(f"Final Canopy = {pct_tree:.2f}% + {est_hidden_trees:.2f}% = {final_canopy:.2f}%")
        print("-" * 40)

    # --- 4. GREEN COVER CALCULATION ---
    if verbose: print("\n--- GREEN COVER ESTIMATE ---")

    # Step A: Sum all known green points
    known_green = pct_bare + pct_tree + pct_veg_not_tree + pct_veg_unsure

    if verbose:
        print(f"Step A: Sum all confirmed green points")
        print(
            f"Known Green = {pct_bare:.2f}% + {pct_tree:.2f}% + {pct_veg_not_tree:.2f}% + {pct_veg_unsure:.2f}% = {known_green:.2f}%")

    # Step B: Find proportion of green in the known sample
    known_sample = 100.0 - pct_unsure_total
    green_ratio = known_green / known_sample if known_sample > 0 else 0

    if verbose:
        print(f"\nStep B: Find green proportion in the known sample")
        print(f"Known sample size = 100% - {pct_unsure_total:.2f}% (Total Unsure) = {known_sample:.2f}%")
        print(f"Proportion = {known_green:.2f} / {known_sample:.2f} = {green_ratio:.4f}")

    # Step C: Apply to total Unsure points
    est_hidden_green = pct_unsure_total * green_ratio

    if verbose:
        print(f"\nStep C: Estimate hidden green points")
        print(f"Estimated hidden green = {pct_unsure_total:.2f}% * {green_ratio:.4f} = {est_hidden_green:.2f}%")

    # Step D: Final Green Cover
    final_green = known_green + est_hidden_green

    if verbose:
        print(f"\nStep D: Final Green Cover")
        print(f"Final Green = {known_green:.2f}% + {est_hidden_green:.2f}% = {final_green:.2f}%")
        print("=" * 40 + "\n")


    # --- 5. MARGIN OF ERROR (STANDARD ERROR) ---
    n_total = len(points_df)

    # Calculate SE assuming n_total > 0
    p_canopy = final_canopy / 100
    se_canopy = math.sqrt((p_canopy * (1 - p_canopy)) / n_total) * 100 if n_total > 0 else 0.0

    p_green = final_green / 100
    se_green = math.sqrt((p_green * (1 - p_green)) / n_total) * 100 if n_total > 0 else 0.0

    if verbose:
        print("\n--- FINAL STATISTICAL ESTIMATES (+- SE) ---")
        print(f"Total Sample Size (n): {n_total} points\n")
        print(f"Canopy SE: sqrt(({p_canopy:.4f} * {1 - p_canopy:.4f}) / {n_total}) * 100 = {se_canopy:.2f}%")
        print(f"Green SE:  sqrt(({p_green:.4f} * {1 - p_green:.4f}) / {n_total}) * 100 = {se_green:.2f}%\n")

        print(f"Canopy Cover Estimate: {final_canopy:.1f}% +- {se_canopy:.2f}%")
        print(f"Green Cover Estimate:  {final_green:.1f}% +- {se_green:.2f}%")
        print("=" * 40 + "\n")

    # Return the expanded dictionary
    return {
        'iTree Canopy Cover (%)': final_canopy,
        'iTree Canopy SE (%)': se_canopy,
        'iTree Green Cover (%)': final_green,
        'iTree Green SE (%)': se_green,
        'Total Evaluated Points': n_total
    }

def print_gla_itree_calculations():
    print("""
--- RAW LABEL PERCENTAGES ---
                             Raw Percentage (%)
Manmade                                   44.03
Vegetation (not Tree)                     29.38
Tree                                      19.43
Bare Ground                                2.50
Water                                      2.38
Vegetation (unsure if Tree)                1.25
Unsure                                     1.05

========================================

--- CANOPY COVER ESTIMATE ---
Step A: Find tree proportion in known vegetation
Total known vegetation = 19.43% (Tree) + 29.38% (Veg not Tree) = 48.80%
Proportion = 19.43 / 48.80 = 0.3981

Step B: Estimate hidden trees
Estimated hidden trees = 1.25% (Veg unsure if Tree) * 0.3981 = 0.50%

Step C: Final Canopy Cover
Final Canopy = 19.43% + 0.50% = 19.92%
----------------------------------------

--- GREEN COVER ESTIMATE ---
Step A: Sum all confirmed green points
Known Green = 2.50% + 19.43% + 29.38% + 1.25% = 52.55%

Step B: Find green proportion in the known sample
Known sample size = 100% - 1.05% (Total Unsure) = 98.95%
Proportion = 52.55 / 98.95 = 0.5311

Step C: Estimate hidden green points
Estimated hidden green = 1.05% * 0.5311 = 0.56%

Step D: Final Green Cover
Final Green = 52.55% + 0.56% = 53.11%
========================================

--- FINAL STATISTICAL ESTIMATES (+- SE) ---
Total Sample Size (n): 4000 points

Canopy SE: sqrt((0.1992 * 0.8008) / 4000) * 100 = 0.63%
Green SE:  sqrt((0.5311 * 0.4689) / 4000) * 100 = 0.79%

Canopy Cover Estimate: 19.9% +- 0.63%
Green Cover Estimate:  53.1% +- 0.79%
========================================
    
    """)

def style_comparison_table(df):
    """
    Applies GLA-style formatting and ensures index/headers are clean.
    """
    styler = (
        df.style
        .set_properties(**{
            'border': '1px solid black',
            'text-align': 'center',
            'vertical-align': 'middle',
            'padding': '6px 12px'
        })
        .set_table_styles([
            {'selector': 'th', 'props': [
                ('border', '1px solid black'),
                ('background-color', '#f2f2f2'),
                ('text-align', 'center'),
                ('font-weight', 'bold')
            ]}
        ])
        # FIX 1: Explicitly hide the index column so it doesn't show as a blank column
        .hide(axis='index')
        # Centering the output
        .set_table_attributes('style="margin-left: auto; margin-right: auto; border-collapse: collapse;"')
    )
    return styler

def calculate_ukceh_covers(westminster_mask, ukceh_lcm, canopy_classes, green_only_classes):
    # --- 1. Load the Boundary ---
    # Ensure your Westminster vector is in the same CRS as the raster
    westminster = gpd.read_file(westminster_mask)

    # --- 2. Mask the Raster ---
    with rasterio.open(ukceh_lcm) as src:
        # This "clips" the raster data to only the pixels inside the polygon
        out_image, out_transform = mask(src, westminster.geometry, crop=True)
        data = out_image[0]  # Get the first band

    # --- 3. Count Pixels ---
    # Instead of np.sum(data > 0), use the source's metadata to find the real land
    nodata_value = src.nodata
    total_land_pixels = np.sum((data != nodata_value) & (data != 0))

    count_canopy = np.sum(np.isin(data, canopy_classes))
    count_green_only = np.sum(np.isin(data, green_only_classes))

    # Total Green Cover = Canopy + Other Green Vegetation
    count_total_green = count_canopy + count_green_only

    # --- 4. Calculate Percentages ---
    pct_canopy = (count_canopy / total_land_pixels) * 100
    pct_total_green = (count_total_green / total_land_pixels) * 100

    print(f"UKCEH Westminster Results:\n")
    print(f"Total Pixels Sampled: {total_land_pixels}")
    print(f"Total Canopy Pixels Sampled: {count_canopy}")
    print(f"Total Green Pixels Sampled: {count_total_green} (includes canopy)\n")
    print(f"Canopy Cover: {pct_canopy:.2f}%")
    print(f"Total Green Cover: {pct_total_green:.2f}%")